#pragma once

enum AppState {
  STATE_HOME,
  STATE_MENU,
  STATE_SET_TIME,
  STATE_ALARM,
  STATE_STOPER,
  STATE_DEBUG_STM32,
  STATE_STATS_RESOURCES, // stan do wyświetlania zasobów systemu
  STATE_WIFI_SYNC,
  STATE_TEMPERATURE,
  STATE_HUMIDITY,

  // --- Statystyki ---
  STATE_STATS,          // Menu statystyk (lista z >)
  STATE_STATS_CLICKS,   // Widok samych kliknięć
  STATE_STATS_STEPS,    // Widok kroków L/R
  STATE_STATS_TEMP,     // Widok min/max temperatury
  STATE_STATS_HUM,      // Widok min/max wilgotności

  // --- Zasoby Systemu (Menu + Szczegóły) ---
  STATE_STATS_RESOURCES_MENU,   // Menu zasobów (RAM, CPU, Flash)
  STATE_STATS_RESOURCES_RAM,    // Widok pamięci RAM
  STATE_STATS_RESOURCES_CPU,    // Widok obciążenia CPU
  STATE_STATS_RESOURCES_FLASH,  // Widok pamięci Flash

  // --- Aliasy kompatybilności (stare nazwy bez podkreśleń) ---
  STATEHOME           = STATE_HOME,
  STATEMENU           = STATE_MENU,
  STATESETTIME        = STATE_SET_TIME,
  STATEALARM          = STATE_ALARM,
  STATESTOPER         = STATE_STOPER,
  STATEDEBUGSTM32     = STATE_DEBUG_STM32,
  STATESTATSRESOURCES = STATE_STATS_RESOURCES,
  STATEWIFISYNC       = STATE_WIFI_SYNC,
  STATETEMPERATURE    = STATE_TEMPERATURE,
  STATEHUMIDITY       = STATE_HUMIDITY,

  STATESTATS        = STATE_STATS,
  STATESTATSCLICKS  = STATE_STATS_CLICKS,
  STATESTATSSTEPS   = STATE_STATS_STEPS,
  STATESTATSTEMP    = STATE_STATS_TEMP,
  STATESTATSHUM     = STATE_STATS_HUM,
  STATESTATSRESOURCESMENU   = STATE_STATS_RESOURCES_MENU,
  STATESTATSRESOURCESRAM    = STATE_STATS_RESOURCES_RAM,
  STATESTATSRESOURCESCPU    = STATE_STATS_RESOURCES_CPU,
  STATESTATSRESOURCESFLASH  = STATE_STATS_RESOURCES_FLASH,

  // --- PMS5003 ---
  STATE_PMS5003,        // Menu PMS5003 (lista z >)
  STATE_PMS5003_CF1,    // Menu trybu fabrycsnego (dane bieżące)
  STATE_ENS160_AHT21,   // Menu ENS160 + AHT21 (lista z >)
  STATE_ENS160_AHT21_SUMMARY,
  STATE_ENS160_AHT21_GAS,
  STATE_ENS160_AHT21_GAS_AQI,
  STATE_ENS160_AHT21_GAS_TVOC,
  STATE_ENS160_AHT21_GAS_ECO2,
  STATE_ENS160_AHT21_CLIMATE,
  STATE_ENS160_AHT21_CLIMATE_TEMP,
  STATE_ENS160_AHT21_CLIMATE_HUM,
  STATE_ENS160_AHT21_STATUS,

  // --- Ustawienia (Settings) ---
  STATE_SETTINGS,              // Menu Ustawień (lista z >)
  STATE_SETTINGS_PMS5003,      // Ustawienia PMS5003 (włącz/wyłącz)
  STATE_SETTINGS_BUZZER,       // Ustawienia Buzera (włącz/wyłącz)
  STATE_PMS5003_CF1_PM1,   // Szczegóły PM1.0 w CF=1
  STATE_PMS5003_CF1_PM25,  // Szczegóły PM2.5 w CF=1
  STATE_PMS5003_CF1_PM10,  // Szczegóły PM10 w CF=1
  STATE_PMS5003_ATM,       // Menu trybu atmosferycznego (dane bieżące)
  STATE_PMS5003_ATM_PM1,   // Szczegóły PM1.0 w ATM
  STATE_PMS5003_ATM_PM25,  // Szczegóły PM2.5 w ATM
  STATE_PMS5003_ATM_PM10,  // Szczegóły PM10 w ATM
  STATE_PMS5003_PARTICLES, // Menu liczby cząstek (dane bieżące)
  STATE_PMS5003_PARTICLES_0_3,   // Szczegóły cząstek > 0.3µm
  STATE_PMS5003_PARTICLES_0_5,   // Szczegóły cząstek > 0.5µm
  STATE_PMS5003_PARTICLES_1_0,   // Szczegóły cząstek > 1.0µm
  STATE_PMS5003_PARTICLES_2_5,   // Szczegóły cząstek > 2.5µm
  STATE_PMS5003_PARTICLES_5_0,   // Szczegóły cząstek > 5.0µm
  STATE_PMS5003_PARTICLES_10_0,  // Szczegóły cząstek > 10µm
  STATE_PMS5003_TELEMETRY,       // Telemetria czujnika (błędy, bajty, latencja)

  // --- Aliasy dla PMS5003 ---
  STATEPMS5003          = STATE_PMS5003,
  STATEPMS5003CF1       = STATE_PMS5003_CF1,
  STATEENS160AHT21      = STATE_ENS160_AHT21,
  STATEENS160AHT21SUMMARY = STATE_ENS160_AHT21_SUMMARY,
  STATEENS160AHT21GAS     = STATE_ENS160_AHT21_GAS,
  STATEENS160AHT21GASAQI  = STATE_ENS160_AHT21_GAS_AQI,
  STATEENS160AHT21GASTVOC = STATE_ENS160_AHT21_GAS_TVOC,
  STATEENS160AHT21GASECO2 = STATE_ENS160_AHT21_GAS_ECO2,
  STATEENS160AHT21CLIMATE = STATE_ENS160_AHT21_CLIMATE,
  STATEENS160AHT21CLIMATETEMP = STATE_ENS160_AHT21_CLIMATE_TEMP,
  STATEENS160AHT21CLIMATEHUM  = STATE_ENS160_AHT21_CLIMATE_HUM,
  STATEENS160AHT21STATUS = STATE_ENS160_AHT21_STATUS,
  STATEPMS5003CF1PM1    = STATE_PMS5003_CF1_PM1,
  STATEPMS5003CF1PM25   = STATE_PMS5003_CF1_PM25,
  STATEPMS5003CF1PM10   = STATE_PMS5003_CF1_PM10,
  STATEPMS5003ATM       = STATE_PMS5003_ATM,
  STATEPMS5003ATMPM1    = STATE_PMS5003_ATM_PM1,
  STATEPMS5003ATMPM25   = STATE_PMS5003_ATM_PM25,
  STATEPMS5003ATMPM10   = STATE_PMS5003_ATM_PM10,
  STATEPMS5003PARTICLES = STATE_PMS5003_PARTICLES,
  STATEPMS5003PARTICLES0_3 = STATE_PMS5003_PARTICLES_0_3,
  STATEPMS5003PARTICLES0_5 = STATE_PMS5003_PARTICLES_0_5,
  STATEPMS5003PARTICLES1_0 = STATE_PMS5003_PARTICLES_1_0,
  STATEPMS5003PARTICLES2_5 = STATE_PMS5003_PARTICLES_2_5,
  STATEPMS5003PARTICLES5_0 = STATE_PMS5003_PARTICLES_5_0,
  STATEPMS5003PARTICLES10_0 = STATE_PMS5003_PARTICLES_10_0,
  STATEPMS5003TELEMETRY = STATE_PMS5003_TELEMETRY,

  // --- Aliasy dla Settings ---
  STATESETTINGS = STATE_SETTINGS,
  STATESETTINGSPMS5003 = STATE_SETTINGS_PMS5003,
  STATESETTINGSBUZZER = STATE_SETTINGS_BUZZER
};

enum EditState {
  EDIT_HOURS,
  EDIT_MINUTES,
  EDIT_SECONDS,
  EDIT_DONE,

  // Aliasy kompatybilności
  EDITHOURS   = EDIT_HOURS,
  EDITMINUTES = EDIT_MINUTES,
  EDITSECONDS = EDIT_SECONDS,
  EDITDONE    = EDIT_DONE
};

enum RadioMode {
  WIFI_ONLY = 0, // WiFi ON, BT OFF
  BT_ONLY   = 1, // WiFi OFF, BT ON

  // Aliasy kompatybilności
  WIFIONLY = WIFI_ONLY,
  BTONLY   = BT_ONLY
};

// GLOBALNY STAN APLIKACJI
extern AppState appState;
extern EditState editState;
extern RadioMode radioMode;
